import { Vessel, Passenger, Cargo, Schedule, TrackingLog, OperationalNotification } from '../types';

export const INITIAL_VESSELS: Vessel[] = [
  {
    id: 'ves-001',
    name: 'KM Kelimutu',
    code: 'KLM-01',
    type: 'Penumpang & Ro-Ro',
    passengerCapacity: 920,
    cargoCapacityTon: 1500,
    callSign: 'PKLM',
    captainName: 'Capt. Hendra Wicaksono, M.Mar',
    status: 'Berlayar',
    currentPort: 'Tanjung Priok (Jakarta)',
    destinationPort: 'Tanjung Perak (Surabaya)',
    speedKnots: 16.5,
    lat: -6.10,
    lng: 108.50,
    updatedAt: new Date().toISOString()
  },
  {
    id: 'ves-002',
    name: 'KM Labobar',
    code: 'LBR-02',
    type: 'Penumpang & Ro-Ro',
    passengerCapacity: 3084,
    cargoCapacityTon: 2200,
    callSign: 'PLBR',
    captainName: 'Capt. Bambang Suryadi, M.Mar',
    status: 'Proses Muat',
    currentPort: 'Pelabuhan Soekarno-Hatta (Makassar)',
    destinationPort: 'Pelabuhan Sorong (Papua Barat Daya)',
    speedKnots: 0,
    lat: -5.13,
    lng: 119.41,
    updatedAt: new Date().toISOString()
  },
  {
    id: 'ves-003',
    name: 'KM Sinabung',
    code: 'SNB-03',
    type: 'Penumpang & Ro-Ro',
    passengerCapacity: 1906,
    cargoCapacityTon: 1800,
    callSign: 'PSNB',
    captainName: 'Capt. Rizky Pratama, M.Mar',
    status: 'Bersandar',
    currentPort: 'Tanjung Perak (Surabaya)',
    destinationPort: 'Pelabuhan Soekarno-Hatta (Makassar)',
    speedKnots: 0,
    lat: -7.19,
    lng: 112.73,
    updatedAt: new Date().toISOString()
  },
  {
    id: 'ves-004',
    name: 'MV Meratus Jayapura',
    code: 'MRT-10',
    type: 'Petikemas / Kontainer',
    passengerCapacity: 25,
    cargoCapacityTon: 5400,
    callSign: 'PMRT',
    captainName: 'Capt. Agus Firmansyah',
    status: 'Berlayar',
    currentPort: 'Tanjung Perak (Surabaya)',
    destinationPort: 'Pelabuhan Bitung (Sulawesi Utara)',
    speedKnots: 14.8,
    lat: -2.35,
    lng: 118.90,
    updatedAt: new Date().toISOString()
  },
  {
    id: 'ves-005',
    name: 'KMP Dharma Kencana VII',
    code: 'DK-07',
    type: 'Penumpang & Ro-Ro',
    passengerCapacity: 1050,
    cargoCapacityTon: 1900,
    callSign: 'PDK7',
    captainName: 'Capt. Dwi Santoso',
    status: 'Bersandar',
    currentPort: 'Pelabuhan Semayang (Balikpapan)',
    destinationPort: 'Tanjung Perak (Surabaya)',
    speedKnots: 0,
    lat: -1.27,
    lng: 116.82,
    updatedAt: new Date().toISOString()
  }
];

export const INITIAL_PASSENGERS: Passenger[] = [
  {
    id: 'pas-101',
    ticketNumber: 'TKT-202610-001',
    name: 'Ahmad Syahrul Maulana',
    nik: '3171021405900003',
    gender: 'Laki-laki',
    age: 34,
    phone: '081234567890',
    vesselId: 'ves-001',
    vesselName: 'KM Kelimutu',
    originPort: 'Tanjung Priok (Jakarta)',
    destinationPort: 'Tanjung Perak (Surabaya)',
    departureDate: '2026-10-02 08:00',
    cabinClass: 'VIP',
    seatNumber: 'VIP-04',
    ticketPrice: 650000,
    luggageKg: 20,
    status: 'Sudah Boarding',
    createdAt: new Date().toISOString()
  },
  {
    id: 'pas-102',
    ticketNumber: 'TKT-202610-002',
    name: 'Siti Rahmawati Putri',
    nik: '3275034509930005',
    gender: 'Perempuan',
    age: 29,
    phone: '082198765432',
    vesselId: 'ves-001',
    vesselName: 'KM Kelimutu',
    originPort: 'Tanjung Priok (Jakarta)',
    destinationPort: 'Tanjung Perak (Surabaya)',
    departureDate: '2026-10-02 08:00',
    cabinClass: 'Kelas 1',
    seatNumber: '1A-12',
    ticketPrice: 420000,
    luggageKg: 15,
    status: 'Sudah Boarding',
    createdAt: new Date().toISOString()
  },
  {
    id: 'pas-103',
    ticketNumber: 'TKT-202610-003',
    name: 'Budi Santoso Nugroho',
    nik: '3578011208850001',
    gender: 'Laki-laki',
    age: 41,
    phone: '081377889900',
    vesselId: 'ves-002',
    vesselName: 'KM Labobar',
    originPort: 'Pelabuhan Soekarno-Hatta (Makassar)',
    destinationPort: 'Pelabuhan Sorong (Papua Barat Daya)',
    departureDate: '2026-10-02 16:30',
    cabinClass: 'Ekonomi',
    seatNumber: 'DEK-E-105',
    ticketPrice: 285000,
    luggageKg: 25,
    status: 'Check-in',
    createdAt: new Date().toISOString()
  },
  {
    id: 'pas-104',
    ticketNumber: 'TKT-202610-004',
    name: 'Dewi Lestari Kusuma',
    nik: '7371056512960002',
    gender: 'Perempuan',
    age: 28,
    phone: '085244556677',
    vesselId: 'ves-002',
    vesselName: 'KM Labobar',
    originPort: 'Pelabuhan Soekarno-Hatta (Makassar)',
    destinationPort: 'Pelabuhan Sorong (Papua Barat Daya)',
    departureDate: '2026-10-02 16:30',
    cabinClass: 'Bisnis',
    seatNumber: 'B2-08',
    ticketPrice: 380000,
    luggageKg: 18,
    status: 'Menunggu',
    createdAt: new Date().toISOString()
  },
  {
    id: 'pas-105',
    ticketNumber: 'TKT-202610-005',
    name: 'Ir. Wahyu Hidayat',
    nik: '6471011504780004',
    gender: 'Laki-laki',
    age: 48,
    phone: '081122334455',
    vesselId: 'ves-005',
    vesselName: 'KMP Dharma Kencana VII',
    originPort: 'Pelabuhan Semayang (Balikpapan)',
    destinationPort: 'Tanjung Perak (Surabaya)',
    departureDate: '2026-10-03 10:00',
    cabinClass: 'VIP',
    seatNumber: 'VIP-01',
    ticketPrice: 750000,
    luggageKg: 30,
    status: 'Check-in',
    createdAt: new Date().toISOString()
  }
];

export const INITIAL_CARGOS: Cargo[] = [
  {
    id: 'crg-201',
    billOfLading: 'BL-JKT-SBY-8801',
    shipper: 'PT Indofood Sukses Makmur Tbk',
    consignee: 'CV Berkah Jawa Timur Mandiri',
    cargoType: 'Petikemas 40ft',
    itemDescription: 'Bahan Pokok Sembako & Mie Instan (Food Grade)',
    weightTon: 24.5,
    volumeCbm: 68,
    containerOrVehicleNo: 'MRTU-402918-2',
    vesselId: 'ves-001',
    vesselName: 'KM Kelimutu',
    deckPosition: 'Palka Bawah #1',
    originPort: 'Tanjung Priok (Jakarta)',
    destinationPort: 'Tanjung Perak (Surabaya)',
    freightFee: 14500000,
    status: 'On-Board',
    hazardous: 'Non-B3',
    createdAt: new Date().toISOString()
  },
  {
    id: 'crg-202',
    billOfLading: 'BL-SBY-MKS-8802',
    shipper: 'PT Astra International Logistic',
    consignee: 'PT Bosowa Berlian Motor Makassar',
    cargoType: 'Kendaraan Truk/Fuso',
    itemDescription: 'Truk Ekspedisi Muatan Komersial Baru (Fuso Fighter)',
    weightTon: 14.0,
    volumeCbm: 45,
    containerOrVehicleNo: 'B 9844 UZX / CHS-991',
    vesselId: 'ves-003',
    vesselName: 'KM Sinabung',
    deckPosition: 'Car Deck #2',
    originPort: 'Tanjung Perak (Surabaya)',
    destinationPort: 'Pelabuhan Soekarno-Hatta (Makassar)',
    freightFee: 9800000,
    status: 'Siap Muat',
    hazardous: 'Non-B3',
    createdAt: new Date().toISOString()
  },
  {
    id: 'crg-203',
    billOfLading: 'BL-MKS-SRG-8803',
    shipper: 'PT Samudera Bahari Coldchain',
    consignee: 'PT Papua Mina Frozen Seafood',
    cargoType: 'Reefer / Berpendingin',
    itemDescription: 'Ikan Segar Ekspor & Hasil Laut Cold Storage (-20°C)',
    weightTon: 18.2,
    volumeCbm: 54,
    containerOrVehicleNo: 'RF-CO-77218-0',
    vesselId: 'ves-002',
    vesselName: 'KM Labobar',
    deckPosition: 'Reefer Deck #3 Plug-4',
    originPort: 'Pelabuhan Soekarno-Hatta (Makassar)',
    destinationPort: 'Pelabuhan Sorong (Papua Barat Daya)',
    freightFee: 22000000,
    status: 'Loading',
    hazardous: 'Non-B3',
    createdAt: new Date().toISOString()
  },
  {
    id: 'crg-204',
    billOfLading: 'BL-SBY-BTG-8804',
    shipper: 'PT Semen Indonesia Logistik',
    consignee: 'PT Sulawesi Karya Graha',
    cargoType: 'Curah / Bulk',
    itemDescription: 'Semen Sak Konstruksi Portland Type 1 (Palletized)',
    weightTon: 35.0,
    volumeCbm: 42,
    containerOrVehicleNo: 'PALLET-BLK-140',
    vesselId: 'ves-004',
    vesselName: 'MV Meratus Jayapura',
    deckPosition: 'Palka Tengah #2',
    originPort: 'Tanjung Perak (Surabaya)',
    destinationPort: 'Pelabuhan Bitung (Sulawesi Utara)',
    freightFee: 18500000,
    status: 'On-Board',
    hazardous: 'Non-B3',
    createdAt: new Date().toISOString()
  }
];

export const INITIAL_SCHEDULES: Schedule[] = [
  {
    id: 'sch-301',
    voyageNumber: 'VOY/2026/X/041',
    vesselName: 'KM Kelimutu',
    originPort: 'Tanjung Priok (Jakarta)',
    destinationPort: 'Tanjung Perak (Surabaya)',
    berth: 'Dermaga 106 Nusantara',
    departureTime: '2026-10-02 08:00',
    arrivalTime: '2026-10-03 04:30',
    status: 'Berlayar',
    estimatedPassengers: 840,
    estimatedCargoTon: 1250
  },
  {
    id: 'sch-302',
    voyageNumber: 'VOY/2026/X/042',
    vesselName: 'KM Labobar',
    originPort: 'Pelabuhan Soekarno-Hatta (Makassar)',
    destinationPort: 'Pelabuhan Sorong (Papua Barat Daya)',
    berth: 'Dermaga Hatta 02',
    departureTime: '2026-10-02 16:30',
    arrivalTime: '2026-10-04 11:00',
    status: 'Boarding',
    estimatedPassengers: 2450,
    estimatedCargoTon: 1980
  },
  {
    id: 'sch-303',
    voyageNumber: 'VOY/2026/X/043',
    vesselName: 'KM Sinabung',
    originPort: 'Tanjung Perak (Surabaya)',
    destinationPort: 'Pelabuhan Soekarno-Hatta (Makassar)',
    berth: 'Dermaga Jamrud Utara',
    departureTime: '2026-10-02 21:00',
    arrivalTime: '2026-10-04 06:00',
    status: 'Tepat Waktu',
    estimatedPassengers: 1420,
    estimatedCargoTon: 1400
  },
  {
    id: 'sch-304',
    voyageNumber: 'VOY/2026/X/044',
    vesselName: 'MV Meratus Jayapura',
    originPort: 'Tanjung Perak (Surabaya)',
    destinationPort: 'Pelabuhan Bitung (Sulawesi Utara)',
    berth: 'Terminal Berlian',
    departureTime: '2026-10-01 22:00',
    arrivalTime: '2026-10-05 14:00',
    status: 'Berlayar',
    estimatedPassengers: 12,
    estimatedCargoTon: 4800
  }
];

export const INITIAL_TRACKING_LOGS: TrackingLog[] = [
  {
    id: 'log-401',
    vesselName: 'KM Kelimutu',
    voyageNumber: 'VOY/2026/X/041',
    eventType: 'Keberangkatan',
    description: 'Kapal bertolak dari Dermaga 106 Tanjung Priok menuju Tanjung Perak setelah pengecekan manifest tuntas.',
    location: 'Tanjung Priok (Jakarta)',
    officer: 'Bripka Bambang (KPLP)',
    timestamp: '2026-10-02 08:15'
  },
  {
    id: 'log-402',
    vesselName: 'KM Kelimutu',
    voyageNumber: 'VOY/2026/X/041',
    eventType: 'Izin Syahbandar (SPB)',
    description: 'Surat Persetujuan Berlayar (SPB No. SPB/098/X/2026) resmi diterbitkan oleh Kantor KSOP Utama Tanjung Priok.',
    location: 'Kantor KSOP Utama Priok',
    officer: 'Drs. H. Mulyadi (Syahbandar)',
    timestamp: '2026-10-02 07:45'
  },
  {
    id: 'log-403',
    vesselName: 'KM Labobar',
    voyageNumber: 'VOY/2026/X/042',
    eventType: 'Loading Crane',
    description: 'Pemuatan 14 unit petikemas dan 8 unit kendaraan roda 4 di Car Deck #1 selesai diawasi tim stevedoring.',
    location: 'Dermaga Hatta 02 Makassar',
    officer: 'Supriyanto (Superintendent)',
    timestamp: '2026-10-02 14:20'
  },
  {
    id: 'log-404',
    vesselName: 'KM Labobar',
    voyageNumber: 'VOY/2026/X/042',
    eventType: 'Check-in Penumpang',
    description: 'Gerbang boarding dibuka untuk 2.450 calon penumpang. Pemeriksaan tiket dan barcode NIK berjalan tertib.',
    location: 'Terminal Penumpang Anging Mammiri',
    officer: 'Nurul Aini (Petugas Pintu 1)',
    timestamp: '2026-10-02 15:00'
  },
  {
    id: 'log-405',
    vesselName: 'MV Meratus Jayapura',
    voyageNumber: 'VOY/2026/X/044',
    eventType: 'Cuaca Laut',
    description: 'Peringatan BMKG Maritim: Tinggi gelombang di perairan Selat Makassar bagian tengah berkisar 1.5 - 2.2 meter, angin 18 knot.',
    location: 'Selat Makassar (02°21\'S 118°54\'E)',
    officer: 'Perwira Jaga Deck',
    timestamp: '2026-10-02 12:00'
  }
];

export const INITIAL_NOTIFICATIONS: OperationalNotification[] = [
  {
    id: 'notif-501',
    title: 'Kapasitas Palka KM Labobar Mendekati Batas Maksimal (90%)',
    message: 'Total tonase muatan kargo telah mencapai 1.980 Ton dari batas kapasitas 2.200 Ton. Segera tutup pemesanan slot kontainer baru.',
    type: 'warning',
    category: 'Muatan',
    read: false,
    timestamp: '10 menit yang lalu'
  },
  {
    id: 'notif-502',
    title: 'Peringatan Cuaca Gelombang Laut BMKG Maritim',
    message: 'Perkiraan gelombang tinggi 2.0 - 2.5 m di Laut Jawa bagian timur. Nahkoda KM Kelimutu diinstruksikan menjaga kecepatan ekonomis 15 knot.',
    type: 'alert',
    category: 'Cuaca',
    read: false,
    timestamp: '25 menit yang lalu'
  },
  {
    id: 'notif-503',
    title: 'Manifest Penumpang KM Kelimutu Diverifikasi',
    message: 'Total 840 penumpang telah selesai boarding di Dermaga 106. Dokumen manifest final telah dikirim ke KSOP Tanjung Priok.',
    type: 'success',
    category: 'Penumpang',
    read: true,
    timestamp: '1 jam yang lalu'
  },
  {
    id: 'notif-504',
    title: 'Jadwal Docking & Perawatan Armada',
    message: 'KMP Dharma Kencana VII dijadwalkan inspeksi ramp door dan lambung di PT Dok Perkapalan Surabaya tanggal 15 Oktober 2026.',
    type: 'info',
    category: 'Jadwal',
    read: true,
    timestamp: '3 jam yang lalu'
  }
];

export const PORT_LIST = [
  'Tanjung Priok (Jakarta)',
  'Tanjung Perak (Surabaya)',
  'Pelabuhan Soekarno-Hatta (Makassar)',
  'Pelabuhan Belawan (Medan)',
  'Pelabuhan Semayang (Balikpapan)',
  'Pelabuhan Sorong (Papua Barat Daya)',
  'Pelabuhan Bitung (Sulawesi Utara)',
  'Pelabuhan Trisakti (Banjarmasin)',
  'Pelabuhan Dwikora (Pontianak)',
  'Pelabuhan Benoa (Bali)',
  'Pelabuhan Tenau (Kupang)'
];
